version: '3'
services:
  srsue2_5g_zmq:
    image: docker_srslte
    container_name: srsue2_5g_zmq
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - ./srslte:/mnt/srslte
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ue2_5g_zmq
    expose:
      - "2000/tcp"
      - "2002/tcp"
    networks:
      default:
        ipv4_address: ${SRS_UE2_IP}
networks:
  default:
    external:
      name: docker_open5gs_default
